INSERT INTO account VALUES (DEFAULT, 'Alex', 1000);
INSERT INTO account VALUES (DEFAULT, 'Billy', 1000);
INSERT INTO account VALUES (DEFAULT, 'Chris', 1000);

INSERT INTO users VALUES (DEFAULT, 'Axel', 'admin', '$2a$10$PrI5Gk9L.tSZiW9FXhTS8O8Mz9E97k2FZbFvGFFaSsiTUIl.TCrFu', DEFAULT);
INSERT INTO users VALUES (DEFAULT, 'Berg', 'user', '$2a$10$PrI5Gk9L.tSZiW9FXhTS8O8Mz9E97k2FZbFvGFFaSsiTUIl.TCrFu', DEFAULT);

INSERT INTO roles VALUES (DEFAULT, 'ROLE_ADMIN');
INSERT INTO roles VALUES (DEFAULT, 'ROLE_USER');

INSERT INTO users_roles VALUES (1, 1);
INSERT INTO users_roles VALUES (1, 2);
INSERT INTO users_roles VALUES (2, 2);